config/routes.rb
Rails.application.routes.draw do
  get 'about' => 'pages#about'
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :orders

  resources :line_items do
    member do
      patch "decrement"
    end
  end

  resources :carts
  root to: "store#index", as: 'store_index'
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item.price = product.price
    current_item.save
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :order, optional: true
  belongs_to :cart

  def total_price
    price * quantity
  end
end

app/models/order.rb
require 'pago'

class Order < ApplicationRecord
  has_many :line_items, dependent: :destroy
  validates :name, :address, :email, presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
                              :message => 'please enter a valid email'

  def self.pay_types
    ['Credit card', 'Check', 'Purchase order']
  end

   validates :pay_type, inclusion: Order.pay_types

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

  def charge!(pay_type_params)
    payment_details = {}
    payment_method = nil

    case pay_type
    when "Check"
      payment_method = :check
      payment_details[:routing] = pay_type_params[:routing_number]
      payment_details[:account] = pay_type_params[:account_number]
    when "Credit card"
      payment_method = :credit_card
      month,year = pay_type_params[:expiration_date].split(//)
      payment_details[:cc_num] = pay_type_params[:credit_card_number]
      payment_details[:expiration_month] = month
      payment_details[:expiration_year] = year
    when "Purchase order"
      payment_method = :po
      payment_details[:po_num] = pay_type_params[:po_number]
    end

    payment_result = Pago.make_payment(
      order_id: id,
      payment_method: payment_method,
      payment_details: payment_details
    )

    if payment_result.succeeded?
      OrderMailer.received(self).deliver_later
    else
      raise payment_result.error
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  has_many :line_items
  has_many :orders, through: :line_items

  validates :title, :description, :price, presence: true
  validates :title, uniqueness: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  validate :image_format
  validate :image_size

  before_destroy :ensure_not_referenced_by_any_line_item

  private

  def image_format
    if image.attached? && !image.attachment.blob.content_type.in?(%w(image/png image/jpeg image/jpg))
      errors.add(:image, ' must be an image file')
      throw :abort
    end
  end

  def image_size
    if image.attached? && image.blob.byte_size > 5.megabytes
      errors.add(:image, ' is too big')
      throw :abort
    end
  end

  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, 'Line Items present')
      throw :abort
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  has_secure_password

  after_destroy :ensure_an_admin_remains

  class Error < StandardError
  end

  private

  def ensure_an_admin_remains
    if User.count.zero?
      raise Error.new "Can't delete last user"
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_orders = Order.count
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    redirect_back(fallback_location: store_index_url) if session[:cart_id] != @cart.id
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to store_index_url }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to store_index_url, notice: 'Your Cart is currently empty.' }
      format.js { redirect_to store_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_index_url, notice: 'Invalid cart'
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authorize

  def about
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_if(condition, record)
    if condition
      render record
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def pay_type_list
    Order.pay_types.collect { |type| [type, type] }
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/index.html.erb
<div class="ui horizontal list">
  <div class="active item" href="/admin">Home</div>
  <div class="item"><%= link_to 'Orders', orders_path, class: "item" %></div>
  <div class="item"><%= link_to 'Products', products_path %></div>
  <div class="item"><%= link_to 'Users', users_path %></div>
</div>

<h1>Welcome</h1>
<p>
  It's <%= Time.now %>.
  We have <%= link_to pluralize(@total_orders, "order"), orders_path %>.
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Pragprog Books Online Store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,300,700" rel="stylesheet" type="text/css">
    <link href="/assets/semantic.css" rel="stylesheet">
    <link href="/assets/semantic.min.css" rel="stylesheet">
  </head>

  <body>
    <div class="ui secondary pointing menu">
      <a class="item" href="/">
        Home
      </a>
      <a class="item" href="/about">
        About this project
      </a>
      <div class="right menu">
        <a class="ui item" href="https://github.com/stefannibrasil/demo" target="_blank">
          Github
        </a>
        <% if session[:user_id] %>
          <%= link_to 'Dashboard', admin_path, class: "ui item" %>
          <%= link_to 'Logout', logout_path, method: :delete, class: "ui item" %>
        <% end %>
      </div>
    </div>
    <% if notice %>
      <div class="ui yellow message">
        <aside id="notice"><%= notice %></aside>
      </div>
    <% end %>
    <div class="row three column">
      <div class="column">
        <br>
        <div class="ui right floated compact basic segment stepper">
          <div id="cart">
            <%= render_if @cart && @cart.line_items.any?, @cart %>
          </div>
        </div>
        <div class="ui left floated compact basic segment stepper">
          <main class='<%= controller.controller_name %>'>
            <%= yield %>
          </main>
        </div>
      </div>
    </div>
    
  </body>
  <script src="/assets/jquery-3.1.1.min.js" type="text/javascript"></script>
  <script src="/assets/semantic.js" type="text/javascript"></script>
  <script src="/assets/semantic.min.js" type="text/javascript"></script>
</html>

app/views/pages/about.html.erb
<h1 class="ui header">Hello,</h1>

<div class="content">
  <p>Thanks for checking it out this demo project.</p>
  <p>This basic e-commerce was built following the <a class="item" href="hrefttps://pragprog.com/book/rails51/agile-web-development-with-rails-5-1">Agile Web Development with Rails 5.1</a> book tutorial.</p>
</div>

<div class="ui list">
  <div class="item">Ruby on Rails 5.2</div>
  <div class="item">Javascript</div>
  <div class="item">React</div>
  <div class="item">AWS S3</div>
  <div class="item">Postgres</div>
  <div class="item">Semantic UI</div>
</div>

<div class="content">
  <p>The features included are: consumers can browse the products, add items to a cart and "purchase an order" (no payment included). </p>
  <p>The store owner, who must be authenticated first, can create products, track orders and invite new admin users.</p>
  <p>Check it out the <a class="item" href="https://github.com/stefannibrasil/demo" target="_blank">source code</a> or contact me at stefannibrasil at gmail dot com.</p>
</div>